interval_minutes = 5
max_pages_per_channel = 8
lookback_days = 1
proxy_type = "None"
proxy_host = ""
proxy_port = 1080
proxy_username = ""
proxy_password = ""

[protocol_rules.vmess]
enabled = true
max_count = 500

[protocol_rules.vless]
enabled = true
max_count = 500

[protocol_rules.trojan]
enabled = true
max_count = 500

[protocol_rules.ss]
enabled = true
max_count = 500

[protocol_rules.ssr]
enabled = true
max_count = 500

[protocol_rules.tuic]
enabled = true
max_count = 500

[protocol_rules.hysteria]
enabled = true
max_count = 500

[protocol_rules.hysteria2]
enabled = true
max_count = 500

[protocol_rules.hy2]
enabled = true
max_count = 500

[protocol_rules.juicity]
enabled = true
max_count = 500

[protocol_rules.snell]
enabled = true
max_count = 500

[protocol_rules.anytls]
enabled = true
max_count = 500

[protocol_rules.ssh]
enabled = true
max_count = 500

[protocol_rules.wireguard]
enabled = true
max_count = 500

[protocol_rules.wg]
enabled = true
max_count = 500

[protocol_rules.warp]
enabled = true
max_count = 500

[protocol_rules.socks]
enabled = true
max_count = 500

[protocol_rules.socks4]
enabled = true
max_count = 500

[protocol_rules.socks5]
enabled = true
max_count = 500

[protocol_rules.tg]
enabled = true
max_count = 500

[protocol_rules.dns]
enabled = true
max_count = 500

[protocol_rules.nm-dns]
enabled = true
max_count = 500

[protocol_rules.nm-vless]
enabled = true
max_count = 500

[protocol_rules.slipnet-enc]
enabled = true
max_count = 500

[protocol_rules.slipnet]
enabled = true
max_count = 500

[protocol_rules.slipstream]
enabled = true
max_count = 500

[protocol_rules.dnstt]
enabled = true
max_count = 500
